//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_User()
        {
            this.App_Address = new HashSet<App_Address>();
            this.App_Car_Pool = new HashSet<App_Car_Pool>();
            this.App_Takes = new HashSet<App_Takes>();
        }
    
        public int user_id { get; set; }
        public int phone_No { get; set; }
        public string user_name { get; set; }
        public string email { get; set; }
        public string user_password { get; set; }
        public string user_description { get; set; }
        public byte[] profile_picture { get; set; }
        public int address_id { get; set; }
        public string gender { get; set; }
        public bool black_list { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Address> App_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Car_Pool> App_Car_Pool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Takes> App_Takes { get; set; }
    }
}
