//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Feedback
    {
        public int car_pool_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime created_date { get; set; }
        public string feedback_description { get; set; }
        public int rating { get; set; }
    
        public virtual App_Car_Pool App_Car_Pool { get; set; }
    }
}
