//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Takes
    {
        public int user_id { get; set; }
        public int car_pool_id { get; set; }
        public int no_of_seats_booked { get; set; }
        public System.DateTime booking_date { get; set; }
        public System.DateTime unbook_date { get; set; }
    
        public virtual App_Car_Pool App_Car_Pool { get; set; }
        public virtual App_User App_User { get; set; }
    }
}
