//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Address
    {
        public int address_id { get; set; }
        public int house_no { get; set; }
        public int block { get; set; }
        public int street { get; set; }
        public string area { get; set; }
        public string town { get; set; }
        public int user_id { get; set; }
    
        public virtual App_User App_User { get; set; }
    }
}
