//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Car_Pool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Car_Pool()
        {
            this.App_Driver_Schedule = new HashSet<App_Driver_Schedule>();
            this.App_Feedback = new HashSet<App_Feedback>();
            this.App_Takes = new HashSet<App_Takes>();
        }
    
        public int car_pool_id { get; set; }
        public System.DateTime car_pool_created_date { get; set; }
        public string to_ { get; set; }
        public string from_ { get; set; }
        public System.DateTime effective_from { get; set; }
        public System.DateTime effective_to { get; set; }
        public int no_of_seats_available { get; set; }
        public int cost_per_seat { get; set; }
        public bool round_trip { get; set; }
        public int wait_time { get; set; }
        public string description { get; set; }
        public int approx_reach_time { get; set; }
        public bool smoking { get; set; }
        public bool food { get; set; }
        public int user_id { get; set; }
    
        public virtual App_User App_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Driver_Schedule> App_Driver_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Feedback> App_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Takes> App_Takes { get; set; }
    }
}
