//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialTravel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialTravel : DbContext
    {
        public SocialTravel()
            : base("name=SocialTravel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App_Address> App_Address { get; set; }
        public virtual DbSet<App_Car_Pool> App_Car_Pool { get; set; }
        public virtual DbSet<App_Driver_Schedule> App_Driver_Schedule { get; set; }
        public virtual DbSet<App_Feedback> App_Feedback { get; set; }
        public virtual DbSet<App_Takes> App_Takes { get; set; }
        public virtual DbSet<App_User> App_User { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
